### ISSUE TITLE
refactor: Plumb through context

### ISSUE THREAD

**Issue by eddiezane** [zarf-dev/zarf#2365]
### Describe what should be investigated or refactored

As of opening this issue there are ~50 uses of `context.TODO` throughout the codebase. We should refactor these library functions to accept a context.

### Links to any relevant code

https://github.com/search?q=repo%3Adefenseunicorns%2Fzarf+NOT+path%3A*test*+context.TODO&type=code&p=1

### Additional context

While we could create additional `GetPodsWithContext` functions it might be better to bite the bullet and make this as part of a breaking change.

**Comment by phillebaba** [comment]
Relates to #2592 and #2594
