### ISSUE TITLE
Improved image push progress bar support for long image names

### ISSUE THREAD

**Issue by blancharda** [zarf-dev/zarf#2651]
### Is your feature request related to a problem? Please describe.
When pushing images with long paths, the Zarf image push output tends to strobe between `Pushing <x> images` and a truncated message with the name of the image (shown in the video below).

I believe this may be a result of the [default max line width (100c)](https://github.com/defenseunicorns/zarf/blob/main/src/pkg/message/progress.go#L33) in the progress bar.

Ironbank images (as a common example) tend to be quite long due to the repository folder structure:
```
registry1.dso.mil/ironbank/tetrate/istio/proxyv2:1.22.1-tetratefips-v0-zarf-3754112098
```

At 87 characters^, this image name leaves little room on the progress bar line.

### Proposed solution(s)
* Increase the default width to 120 characters (or some other arbitrary length to support longer format image names)
* Separate the progress bar output from the name of the image being pushed (more lines)

### Additional context
Example:
https://github.com/defenseunicorns/zarf/assets/9499393/7d27784e-0bcc-4889-8e6f-d6eef6d0a8a0

**Comment by phillebaba** [comment]
Worth considering for #2588

**Comment by AustinAbro321** [comment]
This is actually not related to long image names. The flashing happens regardless. I believe I have a solution
