### ISSUE TITLE
`zarf connect <connect-name> --local-port` does not work as expected

### ISSUE THREAD

**Issue by lucasrod16** [zarf-dev/zarf#2665]
### Environment
App version: v0.35.0

### Steps to reproduce
1. Initialize a cluster

    ```shell
    zarf init --confirm
    ```
1. Attempt to connect to the Zarf registry using a user-specified local port

    ```shell
    zarf connect registry --local-port 8080
    ```

### Expected result
Zarf forwards traffic from `127.0.0.1:8080` on my local machine to a registry pod in the cluster

### Actual Result
Zarf forwards traffic from `127.0.0.1:<randomly-selected-port>` on my local machine to a registry pod in the cluster

I expect Zarf to use the `--local-port` value that I provided instead of a randomly selected port on my machine

### Visual Proof (screenshots, videos, text, etc)
![Screenshot 2024-06-25 at 2 24 02 PM](https://github.com/defenseunicorns/zarf/assets/87675701/257a6f49-0824-4b00-a61b-c651f153cbb6)
<img width="1413" alt="Screenshot 2024-06-25 at 2 24 37 PM" src="https://github.com/defenseunicorns/zarf/assets/87675701/25871a8b-cce1-461c-870d-04738ef78101">

### Severity/Priority
Low

### Additional Context
This was originally reported in #2661

Workaround is to pass Zarf the name of the service to port-forward to and the remote port the registry is accessible at

```shell
zarf connect --name zarf-connect-registry --local-port 8080 --remote-port 5000
```

**Comment by lucasrod16** [comment]
Here are some links to where the code is

https://github.com/defenseunicorns/zarf/blob/a095700423ae027adcede2c5ba7ee9aad024823a/src/cmd/connect.go#L45-L51
https://github.com/defenseunicorns/zarf/blob/a095700423ae027adcede2c5ba7ee9aad024823a/src/pkg/cluster/tunnel.go#L96-L129
https://github.com/defenseunicorns/zarf/blob/a095700423ae027adcede2c5ba7ee9aad024823a/src/pkg/cluster/tunnel.go#L131-L144
https://github.com/defenseunicorns/zarf/blob/a095700423ae027adcede2c5ba7ee9aad024823a/src/pkg/cluster/tunnel.go#L55-L65

**Comment by chaospuppy** [comment]
Is there a reason beyond need that the members of TunnelInfo are currently unexported?  My initial thought is to populate these argument values directly into TunnelInfo and pass TunnelInfo to Connect(), which would allow us to carry user settings through to ConnectTunnelInfo [here](https://github.com/defenseunicorns/zarf/blob/7288cf2b6c40570d84128fd4ec6673a3277aedee/src/pkg/cluster/tunnel.go#L128).

**Comment by phillebaba** [comment]
There is no specific reason why the properties are not exported, it is more that there is no plan for how an exported API would look. I have wanted to refactor some of the tunneling logic before that.

**Comment by chaospuppy** [comment]
I've taken a first pass at it, I did end up exporting those properties, so if that isn't desired let me know.  I also handle each user input individually to determine if tunnel details should be updated after we determine tunnel info from the supplied target, but I don't know if there's a better way to handle that.
