### ISSUE TITLE
Replace custom retry logic with a single retry function

### ISSUE THREAD

**Issue by phillebaba** [zarf-dev/zarf#2827]
### Describe what should be investigated or refactored
We have a couple of ways to implement retry logic in Zarf. The most common are use of timers or the retry function form the helpers package. The former respects contexts while the latter does not. It would be better if we could decide on a single retry package to use in this function to simplify things.

A suggestion is to switch to using retry-go. This project has been around for a while and is pretty stable.
https://github.com/avast/retry-go

### Links to any relevant code
https://github.com/zarf-dev/zarf/blob/5e77e3816051973c3b5ec3d48be30865b40db5e1/src/pkg/cluster/cluster.go#L82-L120
https://github.com/zarf-dev/zarf/blob/5e77e3816051973c3b5ec3d48be30865b40db5e1/src/internal/packager/images/push.go#L57
https://github.com/zarf-dev/zarf/blob/5e77e3816051973c3b5ec3d48be30865b40db5e1/src/pkg/cluster/namespace.go#L30-L46
https://github.com/zarf-dev/zarf/blob/5e77e3816051973c3b5ec3d48be30865b40db5e1/src/pkg/cluster/state.go#L132-L154

### Additional context
N/A

**Comment by AustinAbro321** [comment]
Small note that there is a `helpers.RetryWithContext` function we use, though from a glance at the retry-go package it seems like a reasonable substitute for both. 
https://github.com/zarf-dev/zarf/blob/5e77e3816051973c3b5ec3d48be30865b40db5e1/src/internal/packager/images/pull.go#L243

**Comment by phillebaba** [comment]
Was not aware of that function, that would also be an option. We just need to look at the pros and cons of bringing in a dependency to do this.

**Comment by salaxander** [comment]
#2027
