### ISSUE TITLE
Include CyclondeDX formatted sbom in the zarf package

### ISSUE THREAD

**Issue by partkyle** [zarf-dev/zarf#2896]
### Describe what should be investigated or refactored

The current SBOM format that is packaged is syft.  As mentioned by [archore](https://anchore.com/sbom/key-things-to-know-about-sboms-and-sbom-standards/#toc-heading-1) (the developer of syft)

> CycloneDX and Software Product Data Exchange (SPDX) are the most commonly used standards.

We should select one of the 2 major standards in the SBOM domain to have broader tooling support.

### Tooling support

Below is a list of tools and the formats that they currently support.

| tool     | syft | cyclonedx          | spdx               |
|----------|------|--------------------|--------------------|
| [syft](https://github.com/anchore/syft) | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark: |
| [trivy](https://github.com/aquasecurity/trivy)    | :x:  | :heavy_check_mark: | :heavy_check_mark: |
| [grype](https://github.com/anchore/grype)    | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| [protobom](https://github.com/protobom/protobom) | :x:  | :heavy_check_mark: | :heavy_check_mark: |

### Alternatives

Protobom is an interesting choice as it aims to support more formats and convert between them without data loss. Many tools in this space are written in go and they could be easily used together.

### Describe a solution you'd like

As my project uses trivy, my preference would be either spdx or cyclonedx. I would lean towards cyclonedx as it is a community run project and moves quicker to incorporate changes than the SPDX foundation project does.

**Comment by daveworth** [comment]
@partkyle as part of your effort can you use the `syft` tooling to convert a given Syft SBOM into either CycloneDX or SPDX to feed to Trivy?  If Zarf _also_ produced SBOMs in one (or both!) of those formats would that also be acceptable rather than replacing the existing technology?

**Comment by jeff-mccoy** [comment]
This was actually why we did this, protobom didnt exist and we didnt want to pick a winner, so instead you can use the `zarf tools sbom convert` to pick your own winner. I don't think this needs to be changed really yet.

**Comment by jeff-mccoy** [comment]
That's also why we didnt embed grype in zarf--even thought it was tempting, we didnt want to prescribe a scanner for that and just wanted an SBOM artifact of some flavor that was portable.

**Comment by partkyle** [comment]
Ok, I can see the reasoning and the embedded tool allowing convert makes sense.

I don't think we need to have anything done at this point. I'll close this out and if there are any other enhancements I think would be good in the future I will make a different issue.

thanks!
