### ISSUE TITLE
Linter running before template vars are applied

### ISSUE THREAD

**Issue by lennard-pfennig-bruker** [zarf-dev/zarf#2908]
### Environment
Device and OS: macOS 14.5 & ubuntu 22
App version: 0.38.2
Kubernetes distro being used: k3s

### Steps to reproduce
1. create zarf.yaml:
```
kind: ZarfPackageConfig
metadata:
  name: "###ZARF_PKG_TMPL_PACKAGE_NAME###"
components:
  - name: files
    files:
      - source: ./zarf.yaml
        target: zarf.yaml
```
2. run `zarf package create --confirm --set PACKAGE_NAME="beer" `

### Expected result
```
> zarf package create --confirm --set PACKAGE_NAME="beer"   
...
✔  Package saved to "zarf-package-beer-arm64.tar.zst" 
```
### Actual Result
```
> zarf package create --confirm --set PACKAGE_NAME="beer"                                                                                                                                   Tue Aug 20 14:43:29 2024

 NOTE  Saving log file to
       /var/folders/bx/hywhy9714_g5st9x3lgd3zjh0000gn/T/zarf-2024-08-20-14-44-43-3045695344.log

 NOTE  Using build directory .

 NOTE  Linting package "beer" at .

     Type  | Path           | Message
     Error | .metadata.name | Does not match pattern '^[a-z0-9][a-z0-9\-]*$'

     ERROR:  failed to create package: found errors in schema
```

### Additional Context
the files component is just so the package builds

**Comment by lennard-pfennig-bruker** [comment]
proposed solution https://github.com/zarf-dev/zarf/issues/2908

**Comment by AustinAbro321** [comment]
Hello thank you for making this issue, this is an important bug to solve, and I appreciate you making a PR. I created a different PR, #2911, to solve this as the schema is auto generated using go tags on the struct + `make docs and schema`. We could have edited those tags, but there are a fair amount of regex tags and I thought templating before checking the schema would be simpler.
