### ISSUE TITLE
Return nil values when returning an error

### ISSUE THREAD

**Issue by phillebaba** [zarf-dev/zarf#2951]
A good practice in Go when returning errors is to return nil or empty data for all other return values. It makes sure there is no other potential confusion on the calling end that the data returned is valid and could be used. 

Here are some examples where we return data and an error.

https://github.com/zarf-dev/zarf/blob/f60b2f48727bbe4be3ebbe90366ecdd4ef8b3f39/src/pkg/utils/yaml.go#L200
https://github.com/zarf-dev/zarf/blob/f60b2f48727bbe4be3ebbe90366ecdd4ef8b3f39/src/pkg/utils/io.go#L43
https://github.com/zarf-dev/zarf/blob/f60b2f48727bbe4be3ebbe90366ecdd4ef8b3f39/src/pkg/zoci/fetch.go#L20
https://github.com/zarf-dev/zarf/blob/f60b2f48727bbe4be3ebbe90366ecdd4ef8b3f39/src/pkg/cluster/zarf.go#L281

This is slightly related to #2950 and could be done in conjunction with it.

**Comment by mkcp** [comment]
I'm intending on skipping packager and extensions (e.g. bigbang) for this to minimize churn with other active refactorings.
