### ISSUE TITLE
Send PTerm tables to os.Stdout not logger.DefaultDestination

### ISSUE THREAD

**Issue by mkcp** [zarf-dev/zarf#3223]
### Is your feature request related to a problem? Please describe.
This is rly more of a bug that I started doing while I was adding in structured logs. Tables needed to be _reinitialized_ when pterm is feature flagged off -- when I put this hack together I passed them `logger.DefaultDestination` which happens to be stderr.

### Describe the behavior you'd like
Sending tables that are definitely "output for users" to stderr isn't very unixy, so let's instead send them to stdout. Let's also declare the writer _outside_ of logger. These are similar but not the same components, so there's no need to use a logger type for output.

Most if not all of of these table prints are well contained to the cmd layer. Here's some examples, this should not be considered an exhaustive list:
- https://github.com/zarf-dev/zarf/blob/36b779f13b4b2f46bc028f093ff1f2ca47b14c77/src/cmd/dev.go#L266
- https://github.com/zarf-dev/zarf/blob/36b779f13b4b2f46bc028f093ff1f2ca47b14c77/src/cmd/dev.go#L317
- https://github.com/zarf-dev/zarf/blob/36b779f13b4b2f46bc028f093ff1f2ca47b14c77/src/cmd/package.go#L240
- https://github.com/zarf-dev/zarf/blob/36b779f13b4b2f46bc028f093ff1f2ca47b14c77/src/cmd/package.go#L286

### Additional context
Ideally we don't have to use this re-initialize hack at all, but that may have to be in scope for a future issue.

**Comment by AustinAbro321** [comment]
Fixed by https://github.com/zarf-dev/zarf/pull/3226
