### ISSUE TITLE
Deploy package in Cluster UI

### ISSUE THREAD

**Issue by Madeline-UX** [zarf-dev/zarf#807]
## User Story
**As** Ashton **I want** to select from a list of packages **so that** I can visually see which packages I am able to deploy into my cluster.

**Given** I am on the main cluster overview page
**When** I click Deploy new package button on deployment page
**Then** the deployment wizard opens
**And** starts with the screen that shows me all of the local Zarf packages on my system
**And** I see the name of the package with a button next to it to deploy
**When** I click deploy package 
**Then** the wizard proceeds to step 2 (Step 1 of init wizard)

## Technical ##

- [x] Zarf needs to search for Zarf packages on the local system
- [x] When user selects package to deploy > $ Zarf package deploy [package name]

**Comment by Madeline-UX** [comment]
@YrrepNoj @jeff-mccoy Can you add your thoughts about how to do this?

**Comment by jeff-mccoy** [comment]
Good news, we already did the backend for that, just need to wire a ui to it 🤓

**Comment by Madeline-UX** [comment]
yay!!

**Comment by Racer159** [comment]
An api endpoint for this exists.
